### PR TITLE
Update ATC fall-back file to latest

### PR DESCRIPTION
**Pull request by aliciaaevans**
It looks like the year was being appended to the fall-back file name and treated as the version also.

@piehld @brindakv Any insight into the following?

1. whether `self.__version` should just be updated to "2023"? Or is there an actual version year I could refer to?
2. Since the unit tests are the only thing consuming that variable, does it matter?
3. Is there any benefit to keeping past versions of the data in github? (currently have `ATC-2021.csv.gz` and `ATC-2018.csv.gz`)

### CODE REVIEW

**Comment by piehld** [comment]
> 1. It looks like the year was being appended to the fall-back file name and treated as the version also.
> 2. whether self.__version should just be updated to "2023"? Or is there an actual version year I could refer to?
> 3. Since the unit tests are the only thing consuming that variable, does it matter?
Is there any benefit to keeping past versions of the data in github? (currently have ATC-2021.csv.gz and ATC-2018.csv.gz)

From the code, it looks like `version` was useful for some reason, though it's hard to tell why without knowing all the history of ATC data. In either case, if only the tests are consuming that variable (as well as the `getAtcVersion()` method), then I'd lean towards setting it to be "2023". Note however that would require you to keep the year in the filename too (or at least require an adjustment [here](https://github.com/rcsb/py-rcsb_utils_chemref/blob/912fca1341c0c31c90906de5325ddc04cc4be7c0/rcsb/utils/chemref/AtcProvider.py#L63)). 

And probably OK to remove older versions of the data files, so long as 2023 has been tested.

Also, as minor of a change as this is, probably good to update the `__init__.py` and `HISTORY.txt` too.

**Comment by aliciaaevans** [comment]
@piehld Good catch on that other line that has the year in the file name. I'm inclined to change it to remove the year from the file name in both places. It seems kind of arbitrary and not done in other files. Currently, the version is hard-coded regardless of whether it is downloaded from the source or from the fall-back, so again it doesn't really seem useful to have it at all.

Another option would be to get the version from here: https://data.bioontology.org/ontologies/ATC/latest_submission but it seems like an extra request for a value that may not be used anywhere.

**Comment by piehld** [comment]
> @piehld Good catch on that other line that has the year in the file name. I'm inclined to change it to remove the year from the file name in both places. It seems kind of arbitrary and not done in other files. Currently, the version is hard-coded regardless of whether it is downloaded from the source or from the fall-back, so again it doesn't really seem useful to have it at all.

True. I guess it's OK to remove the year from the file name then. 

> Another option would be to get the version from here: https://data.bioontology.org/ontologies/ATC/latest_submission but it seems like an extra request for a value that may not be used anywhere.

That could work, but the issue would arise if it gets the most recent version (say, 2023), but ends up using a fall back file  of 2022, which wouldn't be correct. And if it's not used anywhere anyway, then makes no sense.

**Review by piehld — CHANGES_REQUESTED** [review]
In addition to the changes we discussed, just remember to update the init and history files.

**Review by piehld — COMMENTED** [review]
Sorry, just realized that it doesn't make sense to even pass `version` into `__reload` now either, since the reload method doesn't use version anymore.

**Review by piehld — APPROVED** [review]
Thanks for the updates @aliciaaevans. LGTM!

**Pull request merged**
